customCommands:
  - key: "F"
    context: "localBranches"
    command: "git fetch --all --tags --force && git pull"
    description: "Force fetch all tags"
    prompts:
      - type: "confirm"
        title: "Force Fetch"
        body: "Are you sure you want to force fetch all tags?"
